### ISSUE TITLE
app fails to reconnect after sleep resume

### ISSUE THREAD

**Issue by FernandoMiguel** [nextdns/nextdns#13]
when my macbook resumes, nextdns cli app fails to re-connect
```
W: 12:52:43 Endpoint failed: https://dns1.nextdns.io#45.90.28.0: dial tcp 45.90.28.0:443: connect: network is unreachable
W: 12:52:43 Endpoint failed: https://dns2.nextdns.io#45.90.30.0: dial tcp 45.90.30.0:443: connect: network is unreachable
```

**Comment by rs** [comment]
Even after some time it does not resume the connection?

**Comment by FernandoMiguel** [comment]
seems to be better on the latest release.
i'll reopen if it happens again

**Comment by juba** [comment]
I've got the same problem under Linux. I have to restart the `nextdns` service after each sleep / resume to make it work again. 

`systemctl status nextdns` shows this : 

```
nov. 26 09:02:36 L100361 nextdns[18243]: context deadline exceeded
nov. 26 09:02:36 L100361 nextdns[18243]: context deadline exceeded
nov. 26 09:02:36 L100361 nextdns[18243]: context deadline exceeded
nov. 26 09:02:36 L100361 nextdns[18243]: context deadline exceeded
nov. 26 09:02:36 L100361 nextdns[18243]: context deadline exceeded
nov. 26 09:02:37 L100361 nextdns[18243]: context deadline exceeded
nov. 26 09:02:37 L100361 nextdns[18243]: context deadline exceeded
```

I've tried to wait a little but it doesn't seem to resume the connection without a restart.

**Comment by rs** [comment]
I can reproduce the issue to. I will work on a fix.

**Comment by krioso** [comment]
It's not just sleep/resume on Ubuntu Linux - happens on reboot as well.

**Comment by PoorPocketsMcNewHold** [comment]
Same goes, for using it on Raspbian (Debian-based) with the generated .deb file, or on ArcoLinux (Arch-based) by using the AUR.

**Comment by rs** [comment]
The problem is the lack of dependency in the systemd init script. The daemon is launched before network is available and for some reason I’m still investigating, the socket listen does not return an error and does not end up being effective either once network becomes available.

It can be fixed by adding a `After=network-online.target` dependency in the systemd service file. An issue is open on the lib we use to handle that: https://github.com/kardianos/service/issues/77. But I also want to make the daemon able to work whenever it is started.

**Comment by rs** [comment]
Last master should fix the sleep issue, please test and tell me.

**Comment by krioso** [comment]
I see the go file was updated but not sure about the repo - version is 1.1.8. Anyway, did an update a,d also tried the service file edit (below - config ID changed) - still doesn't work on system restart / reboot. A stop / start connects:

sudo nextdns stop
sudo nextdns start

/etc/systemd/system/nextdns.service:

[Unit]
Description=NextDNS DNS53 to DoH proxy.
ConditionFileIsExecutable=/usr/bin/nextdns
After=network-online.target

[Service]
StartLimitInterval=5
StartLimitBurst=10
ExecStart=/usr/bin/nextdns "run" "-report-client-info" "-config-file" "/etc/nextdns.conf" "-config" "<configID>"
Restart=always
RestartSec=120
EnvironmentFile=-/etc/sysconfig/nextdns

[Install]
WantedBy=multi-user.target

**Comment by rs** [comment]
I did not cut a release yet. You have to compile from source to test.

**Comment by krioso** [comment]
All is well with version 1.2.6. After a reinstall and re-run through the install steps, I can reboot and have everything connected to NextDNS.
