### ISSUE TITLE
Synology router (SRM) cannot find nextdns.sh

### ISSUE THREAD

**Issue by csousougen** [nextdns/nextdns#186]
Installation and configuration is succesfull, but afterwards I get the error:

SynologyRouter> nextdns status                                
Error: /usr/local/etc/rc.d/nextdns.sh status: exit status 1: 

Also, I noticed that nextdns.sh is not located in usr/local/etc/rc.d 
Thus, commands like start and stop do not work.

**Comment by csousougen** [comment]
SynologyRouter> DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: synology
INFO: GOARCH: armv7
INFO: GOOS: linux
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): e
SynologyRouter> DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: synology
INFO: GOARCH: armv7
INFO: GOOS: linux
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
DEBUG: Using bin install type
DEBUG: Installing 1.5.4 binary for linux/armv7 to /usr/local/bin/nextdns
DEBUG: Downloading https://github.com/nextdns/nextdns/releases/download/v1.5.4/nextdns_1.5.4_linux_armv7.tar.gz
DEBUG: Start configure
DEBUG: Get configuration ID
DEBUG: Previous config ID: xxxx
NextDNS Configuration ID (default=xxxx): 
DEBUG: Add arg -config=xxxx
Sending your devices name lets you filter analytics and logs by device.
Report device name? [Y|n]: y
DEBUG: Add arg -report-client-info=true
Only use DNS servers located in jurisdictions with strong privacy laws.
This may increase latency.
Enable hardened privacy mode (may increase latency)? [Y|n]: y
DEBUG: Add arg -hardened-privacy=true
DEBUG: Add arg -setup-router=true
Changes DNS settings of the host automatically when nextdns is started.
If you say no here, you will have to manually configure DNS to 127.0.0.1.
Automatically configure host DNS on daemon startup? [Y|n]: n
DEBUG: Add arg -auto-activate=false
NextDNS installed and started using synology init
Error: /usr/local/etc/rc.d/nextdns.sh start: exit status 1: 
ERROR: install: exit 0
DEBUG: Start install loop with CURRENT_RELEASE=1.5.4
DEBUG: NextDNS is up to date (1.5.4)
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=c):

**Comment by rs** [comment]
What do you get for `ls -ld /usr/local/etc/rc.d/`?

**Comment by csousougen** [comment]
> What do you get for `ls -ld /usr/local/etc/rc.d/`?

SynologyRouter> ls -ld /usr/local/etc/rc.d/
drwxr-xr-x    2 root     root          4096 Apr 29 22:37 /usr/local/etc/rc.d/

**Comment by Axam** [comment]
Got the same issue:
`NextDNS installed and started using synology init
Error: /usr/local/etc/rc.d/nextdns.sh start: exit status 1:
ERROR: install: exit 0`

After trying run script got more informative message:
`> /usr/local/etc/rc.d/nextdns.sh start
Starting nextdns
Unable to start
Error: proxy: tcp: listen tcp 127.0.0.1:5342: bind: address already in use`

**Comment by sqwal** [comment]
Same here.

I have a Synology router and a Synology NAS, so I tested on both.

Works fine on the NAS, but same issue with router.

The problem with the NAS is that you cannot get the per-device logs and analytics online. It shows all queries coming from the router (DNS set with NextDNS on the NAS). This is why I'd like to install on the router itself.

Thank you!

**Comment by csousougen** [comment]
> Same here.
> 
> I have a Synology router and a Synology NAS, so I tested on both.
> 
> Works fine on the NAS, but same issue with router.
> 
> The problem with the NAS is that you cannot get the per-device logs and analytics online. It shows all queries coming from the router (DNS set with NextDNS on the NAS). This is why I'd like to install on the router itself.
> 
> Thank you!

Hey, try the following:
1) use the NAS as your dns server on each device, instead of the router 
2) put the devices on /etc/hosts file on NAS 

then the devices will appear on analytics.

**Comment by sqwal** [comment]
Yes, that should work, indeed. I'll try and let you know.

But the whole point was to avoid having to set up the DNS server on each device, hence the one-time router setting ;-) I'm currently switching back and forth between 1.1.1.1 and unlocator DNS (185.37.37.37), depending on my needs, directly on the router, that is so convenient!

**Comment by rs** [comment]
What do you get for `sudo /usr/local/etc/rc.d/nextdns.sh restart`

**Comment by sqwal** [comment]
> What do you get for `sudo /usr/local/etc/rc.d/nextdns.sh restart`

SynologyRouter> sudo /usr/local/etc/rc.d/nextdns.sh restart
-ash: sudo: not found

I can only ssh as root on the router (ssh root@192.168.xx.xx), even if admin user is deactivated.
Not the same behaviour as the NAS (ssh with user account, then sudo -i)

**Comment by rs** [comment]
Please remove sudo

**Comment by sqwal** [comment]
`SynologyRouter> /usr/local/etc/rc.d/nextdns.sh restart
Not running
Starting nextdns
Unable to start
SynologyRouter> Error: proxy: udp: listen udp 127.0.0.1:5342: bind: address already in use
SynologyRouter> `

**Comment by rs** [comment]
And `ps w | grep nextdns`

**Comment by sqwal** [comment]
```
SynologyRouter> ps w | grep nextdns
 6116 root      783m S    /usr/local/bin/nextdns run
12462 root      3892 S    grep nextdns
SynologyRouter> 
```

**Comment by sqwal** [comment]
I'm wondering whereas it could come from the SafeAccess app, which is basically a parental control layer. Usually these kind of application use a self DNS server, don't they?

I'd have to try to deactivate it, if that's something you think might help to resolve the issue...

**Comment by rs** [comment]
Here the problem seem to be the init script not finding the previous process running on restart. The pid is either missing or not containing the right pid.

**Comment by Axam** [comment]
PID is correct. 

> ps | grep nextdns
15014 root      782m S    /usr/local/bin/nextdns run
15519 root      3892 S    grep nextdns

> cat /var/run/nextdns.pid
15014

Failed to start process after install.

**Comment by Axam** [comment]
Looks like real issue is dnsmasq running on port 53. Synology SRM use dnsmasq for DoH and even if you disable DoH dnsmasq still binding to port 53. NextDNS installer changes dhcp-vendor.conf, but that change doesn't work for SRM.

**Comment by rs** [comment]
I don’t have a SRM. Any idea what would work?

**Comment by Axam** [comment]
Don't know good way to disable just DNS. Disabling dnsmasq will turn off DHCP server as well. Also dhcpd.conf is managed by SRM, so changes will be overwritten.

Just as idea. Is it possible to tell NextDNS to don't bring up it's own DNS server? I can configure Synology SRM to use NextDNS as upstream server via DNS over HTTP. In that case discovery part of NextDNS client should work and user will need one manual step to configure DNS.

**Comment by rs** [comment]
Set the dnsmasq port to 0, it will disable dns and keep dhcp.

**Comment by Axam** [comment]
People reported that port 0 disabled DHCP:
https://community.synology.com/enu/forum/17/post/106357?reply=355093 (latest comment)

**Comment by rs** [comment]
This is dnsmasq man page:

```
-p, --port=<port>
Listen on <port> instead of the standard DNS port (53). Setting this to zero completely disables DNS function, leaving only DHCP and/or TFTP.
```

**Comment by Axam** [comment]
You're right about port=0. Installed new version today and noticed that dhcpd-vendor.conf has "port=0". Unfortunately this  didn't help to disable dnsmasq on port 53. I changed script which generates dhcpd.conf and added "port=0" there. In that case dnsmasq didn't listen on port 53.

At this moment I have dnsmasq running and not listening on port 53 and DHCP working fine.
NextDNS still reports startup error. Here is installation log:

> SynologyRouter> DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
> INFO: OS: synology
> INFO: GOARCH: armv7
> INFO: GOOS: linux
> INFO: NEXTDNS_BIN: /usr/local/bin/nextdns
> INFO: LATEST_RELEASE: 1.6.4
> DEBUG: Start install loop with CURRENT_RELEASE=
> DEBUG: NextDNS is not installed
> i) Install NextDNS
> e) Exit
> Choice (default=i): i
> INFO: Installing NextDNS...
> DEBUG: Using bin install type
> DEBUG: Installing 1.6.4 binary for linux/armv7 to /usr/local/bin/nextdns
> DEBUG: Downloading https://github.com/nextdns/nextdns/releases/download/v1.6.4/nextdns_1.6.4_linux_armv7.tar.gz
> DEBUG: Start configure
> DEBUG: Get configuration ID
> DEBUG: Previous config ID: xxxxxx
> NextDNS Configuration ID (default=xxxxxx):
> DEBUG: Add arg -config=xxxxxx
> Sending your devices name lets you filter analytics and logs by device.
> Report device name? [Y|n]:
> DEBUG: Add arg -report-client-info=true
> Only use DNS servers located in jurisdictions with strong privacy laws.
> This may increase latency.
> Enable hardened privacy mode (may increase latency)? [y|N]:
> DEBUG: Add arg -hardened-privacy=false
> DEBUG: Add arg -setup-router=true
> Make nextdns CLI cache responses. This improves latency and reduces the amount
> of queries sent to NextDNS.
> Note that enabling this feature will disable dnsmasq for DNS to avoid double
> caching.
> Enable caching? [Y|n]: n
> Changes DNS settings of the host automatically when nextdns is started.
> If you say no here, you will have to manually configure DNS to 127.0.0.1.
> Automatically setup local host DNS? [Y|n]: n
> DEBUG: Add arg -auto-activate=false
> NextDNS installed and started using synology init
> Error: /usr/local/etc/rc.d/nextdns.sh start: exit status 1:
> 
> Congratulations! NextDNS is now installed.

I don't see any error messages in NextDNS log, process is up and running, listen on 53 and 5353.
Not sure how to confirm that NextDNS discovered hostnames. NextDNS Analytics page still doesn't show device names.

**Comment by Axam** [comment]
After some time logs were updated and I can see device names.

**Comment by tD3rk** [comment]
@Axam, would you be willing to share exactly what you changed and how (step by step) with regard to the script that generates dhcpd.conf? I'm sure there will be plenty of others like myself who are way out of their depths here, but are capable of following simple enough instructions. Ideally this contribution could then make it into the Wiki so that others don't run into the same wall.

**Comment by Axam** [comment]
Added "port=0" at the end of /etc/dhcpd/dhcpd.conf and restarted dhcpd. But that isn't good way.

**Comment by FlorianFranconi** [comment]
Hello, any news? 

Someone managed to install NextDNS on a Synology router?

Thanks

**Comment by florianfranconi** [comment]
Hello, it seems that I always have the same error.

```
Enable instant refresh? [Y|n]: Y
NextDNS installed and started using synology init
Error: /usr/local/etc/rc.d/nextdns.sh start: exit status 1: 
```

**Comment by rs** [comment]
You need to way for the next revision to get this fix

**Comment by florianfranconi** [comment]
Hello,

I upgraded to version 1.9.1

I still have the problem.

```
SynologyRouter> nextdns log
Nov 23 15:45:12 SynologyRouter nextdns [30511]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
```

**Comment by rs** [comment]
1.9.2 should fix that.

**Comment by florianfranconi** [comment]
I don't have the error at the end of the installation, but I still have the error in the logs: 

`Nov 23 16:55:12 SynologyRouter nextdns[22855]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use`

and also when I want to know the status : 

```
SynologyRouter> nextdns status
Error: /usr/local/etc/rc.d/nextdns.sh status: exit status 1: 

```
no error on the other hand when I run ``nextdns start``.

**Comment by rs** [comment]
Did you install a dns server?

**Comment by florianfranconi** [comment]
No I did not install this package on SRM

**Comment by rs** [comment]
Please try to restart the router.

**Comment by florianfranconi** [comment]
I just did it, it didn't change anything

**Comment by rs** [comment]
What do you get for `netstat -lnpe | grep :53`

**Comment by florianfranconi** [comment]
Here is the result: 

```
SynologyRouter> netstat -lnpe | grep :53
tcp 0 0 0.0.0.0:53 0.0.0:* LISTEN 8330/dnsmasq
tcp 0 0 ::%3:53 :::* LISTEN 8330/dnsmasq
udp 0 0 0.0.0.0:5353 0.0.0:* 20254/avahi-daemon:
udp 0 0 0 0.0.0.0:53 0.0.0.0:* 8330/dnsmasq
udp 0 0 ::%15:5353 :::* 20254/avahi-daemon:
udp 0 0 ::%17:53 :::* 8330/dnsmasq
```

**Comment by rs** [comment]
Does it work if you do:

```
nextdns config set -cache-size=0
nextdns restart
```

**Comment by florianfranconi** [comment]
Yes, it seems to be working

```
SynologyRouter> nextdns config set -cache-size=0
SynologyRouter> nextdns restart
SynologyRouter> nextdns status
running
```

I read in the comments above that there was a potential conflict with Port 53 with dnsmasq. Is this conflict still valid after your fix and therefore I have to add `port=0` in the config?

**Comment by rs** [comment]
Next rev will fix this.
