### ISSUE TITLE
Next dns error after upgrading.

### ISSUE THREAD

**Issue by cocoflan** [nextdns/nextdns#465]
can't enable nextdns any more on system after latest update, 

get error "not running" and sometimes it runs and stops again.

Greetings

**Comment by rs** [comment]
Please provide more context. What is the OS/version etc.

**Comment by cocoflan** [comment]
This is what i did now, how can a send the transcript of the installation file to send?

problem stays.


DEBUG=1 sh -c "$(curl -sL https://nextdns.io/install)"
INFO: OS: linuxmint
INFO: GOARCH: amd64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: LATEST_RELEASE: 1.12.1
DEBUG: Start install loop with CURRENT_RELEASE=
DEBUG: NextDNS is not installed
i) Install NextDNS
e) Exit
Choice (default=i): i

**Comment by rs** [comment]
What is the output of `nextdns install`?

**Comment by rs** [comment]
Just past the output of command: `nextdns install`, not the one from curl/installer script.

**Comment by cocoflan** [comment]
nextdns install
Cannot write config: open /etc/nextdns.conf: permission denied

**Comment by rs** [comment]
with sudo please

**Comment by cocoflan** [comment]
sudo nextdns install
NextDNS installed and started using systemd init

and then when i use "nextdns status" i get "not installed"

**Comment by cocoflan** [comment]
nextdns.service - NextDNS DNS53 to DoH proxy.
     Loaded: loaded (/etc/systemd/system/nextdns.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2021-04-19 23:39:53 CEST; 3min 46s ago
    Process: 15055 ExecStart=/usr/bin/nextdns run (code=exited, status=0/SUCCESS)
   Main PID: 15055 (code=exited, status=0/SUCCESS)

Apr 19 23:39:48 delllaptop-Latitude-E5440 nextdns[15055]: Listening on TCP/127.0.0.1:53
Apr 19 23:39:48 delllaptop-Latitude-E5440 nextdns[15055]: Listening on UDP/127.0.0.1:53
Apr 19 23:39:50 delllaptop-Latitude-E5440 systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Activating
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Received signal: terminated
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Stopping NextDNS 1.12.1/linux
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Deactivating
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: NextDNS 1.12.1/linux stopped
Apr 19 23:39:53 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Succeeded.
Apr 19 23:39:53 delllaptop-Latitude-E5440 systemd[1]: Stopped NextDNS DNS53 to DoH proxy..

**Comment by rs** [comment]
what about these:
1. `sudo nextdns status`
2. `systemctl is-active nextdns`
3. `sudo systemctl is-active nextdns`

**Comment by cocoflan** [comment]
sudo nextdns status                         not installed

systemctl is-active nextdns              inactive

sudo systemctl is-active nextdns     inactive

**Comment by cocoflan** [comment]
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: true false false
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: Connected 45.90.28.0:443 (con=36ms tls=67ms, TCP, TLS13)
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: true false false
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: Connected 194.110.115.97:443 (con=23ms tls=30ms, TCP, TLS13)
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: Switching endpoint: https://dns.nextdns.io.#194.110.115.97,2a0d:5642:115:197:5054:ff:fef3:ccd4,185.18.148.91,2>
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: true false true
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: Connected 194.110.115.97:443 (con=31ms tls=28ms, TCP, TLS13)
Apr 19 23:36:33 delllaptop-Latitude-E5440 nextdns[14647]: Switching endpoint: https://dns.nextdns.io.#185.18.148.91,2a04:b80:1:30::2,194.110.115.97,2a0d:5642:115:197:50>
Apr 19 23:36:33 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: State 'stop-sigterm' timed out. Killing.
Apr 19 23:36:33 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Killing process 14647 (nextdns) with signal SIGKILL.
Apr 19 23:36:33 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Killing process 14652 (nextdns) with signal SIGKILL.
Apr 19 23:36:33 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Main process exited, code=killed, status=9/KILL
Apr 19 23:36:33 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Failed with result 'timeout'.
Apr 19 23:36:33 delllaptop-Latitude-E5440 systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
Apr 19 23:37:02 delllaptop-Latitude-E5440 systemd[1]: Started NextDNS DNS53 to DoH proxy..
Apr 19 23:37:02 delllaptop-Latitude-E5440 nextdns[14844]: Starting NextDNS 1.12.1/linux on localhost:53
Apr 19 23:37:02 delllaptop-Latitude-E5440 nextdns[14844]: Listening on TCP/127.0.0.1:53
Apr 19 23:37:02 delllaptop-Latitude-E5440 nextdns[14844]: Listening on UDP/127.0.0.1:53
Apr 19 23:37:07 delllaptop-Latitude-E5440 nextdns[14844]: Activating
Apr 19 23:37:07 delllaptop-Latitude-E5440 systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Apr 19 23:37:07 delllaptop-Latitude-E5440 nextdns[14844]: Activate: NetworkManager resolver management: signal: terminated
Apr 19 23:37:07 delllaptop-Latitude-E5440 nextdns[14844]: Received signal: terminated
Apr 19 23:37:07 delllaptop-Latitude-E5440 nextdns[14844]: Stopping NextDNS 1.12.1/linux
Apr 19 23:37:07 delllaptop-Latitude-E5440 nextdns[14844]: Deactivating
Apr 19 23:37:07 delllaptop-Latitude-E5440 nextdns[14844]: NextDNS 1.12.1/linux stopped
Apr 19 23:37:07 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Succeeded.
Apr 19 23:37:07 delllaptop-Latitude-E5440 systemd[1]: Stopped NextDNS DNS53 to DoH proxy..
Apr 19 23:39:48 delllaptop-Latitude-E5440 systemd[1]: Started NextDNS DNS53 to DoH proxy..
Apr 19 23:39:48 delllaptop-Latitude-E5440 nextdns[15055]: Starting NextDNS 1.12.1/linux on localhost:53
Apr 19 23:39:48 delllaptop-Latitude-E5440 nextdns[15055]: Listening on TCP/127.0.0.1:53
Apr 19 23:39:48 delllaptop-Latitude-E5440 nextdns[15055]: Listening on UDP/127.0.0.1:53
Apr 19 23:39:50 delllaptop-Latitude-E5440 systemd[1]: Stopping NextDNS DNS53 to DoH proxy....
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Activating
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Received signal: terminated
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Stopping NextDNS 1.12.1/linux
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: Deactivating
Apr 19 23:39:53 delllaptop-Latitude-E5440 nextdns[15055]: NextDNS 1.12.1/linux stopped
Apr 19 23:39:53 delllaptop-Latitude-E5440 systemd[1]: nextdns.service: Succeeded.
Apr 19 23:39:53 delllaptop-Latitude-E5440 systemd[1]: Stopped NextDNS DNS53 to DoH proxy..

**Comment by rs** [comment]
1. What is the version of Linux Mint?
2. What do you get for `nextdns config`
3. Can you please try to uninstall/reinstall?

**Comment by cocoflan** [comment]
Linux Mint Release Linux Mint 20.1 Ulyssa 64-bit
Kernel Linux 5.8.0-50-generic x86_64
MATE 1.24.0
log-queries false
cache-max-age 0s
bogus-priv true
use-hosts true
control /var/run/nextdns.sock
cache-size 10MB
auto-activate true
config xxxx
max-ttl 5s
discovery-dns 
detect-captive-portals false
hardened-privacy false
timeout 5s
listen localhost:53
report-client-info true
setup-router false

i did wipe the name on config so normal its numbers and letters of my config xxxx

**Comment by dashsd** [comment]
Same issue on Ubuntu 20.04

**Comment by cocoflan** [comment]
the problem persists after reinstallation.

**Comment by rs** [comment]
v1.31.3 should fix the issue, it will be ready in a few minutes.

**Comment by rs** [comment]
Link 93824fc3fecf11bb70bc1de275c7f54aa3fd1fec

**Comment by dashsd** [comment]
Yes, uninstalling and reinstalling the service doesn't resolve the issue. Upgraded to version 1.12.2 but the issue still persists.

**Comment by cocoflan** [comment]
Ok i will test version v1.31.3 , thx for the info, i will keep you informed if it works.

**Comment by cocoflan** [comment]
Ok version 1.31.3 is working, thx for fixing.

**Comment by cocoflan** [comment]
Thought too soon that it was solved, same problem with new version.

**Comment by rs** [comment]
Please provide logs
