### ISSUE TITLE
Ubiquiti UDMP Problem with Updating

### ISSUE THREAD

**Issue by Veldkornet** [nextdns/nextdns#563]
**Context**
 - CLI Version: 1.35.0
 - Platform: ubios (UDMP 1.11.0-14)

&lt;Describe the bug>

I'm having problems from upgrading NextDNS from 1.35.0 to 1.36.0

```
# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.36.0
u) Upgrade NextDNS from 1.35.0 to 1.36.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
no such directory for freezer.state
Error: `/usr/bin/runc pause 01242cd40801fc2ebbeba4c1c023e3b2ab14b50a08d2effa612d82bb2dd76a03` failed: exit status 1
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u15).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists...
W: Unable to read /etc/apt/-/ - DirectoryExists (2: No such file or directory)
W: Unable to read /etc/apt/sources.list.d/nextdns.list - RealFileExists (2: No such file or directory)
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.35.0).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
u) Upgrade NextDNS from 1.35.0 to 1.36.0
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): 

```

**Comment by janthony6** [comment]
seems the upgrade problems are still there. on the SE, I couldn't upgrade from the most recent snapshot. It would throw an error each time. I also wasn't able to uninstall the latest snapshot. 

I reset the router and 1.37 installed fine. 

On a UDM running 1.11 firmware with 1.36 nextdns upgrade fails too and shows this:

```
# nextdns upgrade
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.0
INFO: Upgrading NextDNS...
no such directory for freezer.state
Error: `/usr/bin/runc pause 5223254e1c1ff6dfd760a00587370862ca01ace2b07f29a2047be8b436a8c597` failed: exit status 1
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
gnupg1 set to manually installed.
curl is already the newest version (7.52.1-5+deb9u15).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Reading package lists...
W: Unable to read /etc/apt/-/ - DirectoryExists (2: No such file or directory)
W: Unable to read /etc/apt/sources.list.d/nextdns.list - RealFileExists (2: No such file or directory)
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.36.0).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.0
INFO: Upgrading NextDNS...
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Get:4 http://deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:5 http://deb.debian.org/debian stretch Release
Hit:6 https://deb.nodesource.com/node_8.x stretch InRelease
Get:7 https://apt.artifacts.ui.com stretch InRelease [7873 B]
Get:8 https://apt-beta.artifacts.ui.com stretch InRelease [3590 B]
Get:9 http://security.debian.org/debian-security stretch/updates/main arm64 Packages [689 kB]
Ign:11 https://apt.artifacts.ui.com stretch/release arm64 Packages
Get:11 https://apt.artifacts.ui.com stretch/release arm64 Packages [28.8 kB]
Ign:12 https://apt-beta.artifacts.ui.com stretch/beta arm64 Packages
Get:12 https://apt-beta.artifacts.ui.com stretch/beta arm64 Packages [15.0 kB]
Fetched 889 kB in 1s (567 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.36.0).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```

**Comment by janthony6** [comment]
with sudo I get:

```
root@UDM-Pro-SE:~# sudo nextdns upgrade
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.1
INFO: Upgrading NextDNS...
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease               
Hit:3 http://deb.debian.org/debian stretch-updates InRelease             
Hit:4 http://deb.debian.org/debian stretch-backports InRelease           
Hit:6 http://deb.debian.org/debian stretch Release                       
Ign:7 https://apt-beta.artifacts.ui.com stretch InRelease
Hit:8 https://apt.artifacts.ui.com stretch InRelease
Get:9 https://apt-beta.artifacts.ui.com stretch Release [2720 B]
Ign:10 https://apt-beta.artifacts.ui.com stretch Release.gpg
Get:11 https://repo.nextdns.io/deb stable InRelease [9398 B]
Hit:5 https://dl.ubnt.com/unifi/debian cloudkey-stable InRelease
Get:13 https://repo.nextdns.io/deb stable/main arm64 Packages [424 B]
Reading package lists... Done   
E: The repository 'https://apt-beta.artifacts.ui.com stretch Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error: exit status 100
```

**Comment by janthony6** [comment]
1.37.1 install on UDM goes like this:

```
# sudo nextdns upgrade
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.1
INFO: Upgrading NextDNS...
no such directory for freezer.state
Error: `/usr/bin/runc pause 5223254e1c1ff6dfd760a00587370862ca01ace2b07f29a2047be8b436a8c597` failed: exit status 1
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u15).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Reading package lists...
W: Unable to read /etc/apt/-/ - DirectoryExists (2: No such file or directory)
W: Unable to read /etc/apt/sources.list.d/nextdns.list - RealFileExists (2: No such file or directory)
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.36.0).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.1
INFO: Upgrading NextDNS...
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Hit:6 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:7 https://apt.artifacts.ui.com stretch InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
nextdns is already the newest version (1.36.0).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```

**Comment by rs** [comment]
Please try to `unifi-os shell` first.

**Comment by janthony6** [comment]
doesn't work either

```
# unifi-os shell
root@ubnt:/# sudo nextdns upgrade
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.1
INFO: Upgrading NextDNS...
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://deb.debian.org/debian stretch Release 
Hit:6 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:7 https://apt.artifacts.ui.com stretch InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nextdns is already the newest version (1.36.0).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
```

**Comment by rs** [comment]
Please uninstall and reinstall from the install script, the source is not installed for some reason.

**Comment by janthony6** [comment]
That doesn't work either. 
```
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.1
u) Upgrade NextDNS from 1.36.0 to 1.37.1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): e
# sudo sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.1
u) Upgrade NextDNS from 1.36.0 to 1.37.1
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): r
INFO: Uninstalling NextDNS...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  nextdns
0 upgraded, 0 newly installed, 1 to remove and 20 not upgraded.
After this operation, 8454 kB disk space will be freed.
(Reading database ... 24233 files and directories currently installed.)
Removing nextdns (1.36.0) ...
#-> ubnt-dpkg-cache remove
removing /data/dpkg-cache/stretch/packages/nextdns_1.36.0_arm64.deb ... done
nextdns: action=remove
<-# ubnt-dpkg-cache remove
#-> ubnt-dpkg-cache configure
<-# ubnt-dpkg-cache configure
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
no such directory for freezer.state
Error: `/usr/bin/runc pause 5223254e1c1ff6dfd760a00587370862ca01ace2b07f29a2047be8b436a8c597` failed: exit status 1
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u15).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nextdns
Error: non zero exit code: 100: OCI runtime error
i) Install NextDNS
e) Exit
Choice (default=i): 
```

**Comment by janthony6** [comment]
I tried installing after uninstalled from unifi-os shell. that got it to install but now its listening on the wrong port.

```
root@ubnt:/# sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.1
i) Install NextDNS
e) Exit
Choice (default=i): r
Invalid choice
i) Install NextDNS
e) Exit
Choice (default=i): i
INFO: Installing NextDNS...
sh: 960: wget: not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.4.11).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://deb.debian.org/debian stretch Release 
Hit:6 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:7 https://apt.artifacts.ui.com stretch InRelease
Get:8 https://repo.nextdns.io/deb stable InRelease [9398 B]
Get:10 https://repo.nextdns.io/deb stable/main arm64 Packages [424 B]
Fetched 9822 B in 1s (7318 B/s)  
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nextdns
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 3061 kB of archives.
After this operation, 8454 kB of additional disk space will be used.
Get:1 https://repo.nextdns.io/deb stable/main arm64 nextdns arm64 1.37.1 [3061 kB]
Fetched 3061 kB in 1s (2807 kB/s)  
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package nextdns.
(Reading database ... 24232 files and directories currently installed.)
Preparing to unpack .../nextdns_1.37.1_arm64.deb ...
Unpacking nextdns (1.37.1) ...
#-> ubnt-dpkg-cache unpack
nextdns: action=unpack, package=/data/dpkg-cache/stretch/packages/nextdns_1.37.1_arm64.deb mark=manual
<-# ubnt-dpkg-cache unpack
Setting up nextdns (1.37.1) ...
NextDNS installed and started using systemd init
```


```
Sep 07 18:28:39 ubnt nextdns[2079]: Starting NextDNS 1.37.1/linux on localhost:53
Sep 07 18:28:39 ubnt nextdns[2079]: Listening on TCP/127.0.0.1:53
Sep 07 18:28:39 ubnt nextdns[2079]: Listening on UDP/127.0.0.1:53
Sep 07 18:28:39 ubnt nextdns[2079]: Startup failed: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
Sep 07 18:28:39 ubnt nextdns[2079]: Error: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use
Sep 07 18:28:39 ubnt systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 18:28:39 ubnt systemd[1]: nextdns.service: Failed with result 'exit-code'.
Sep 07 18:28:39 ubnt systemd[1]: nextdns.service: Consumed 10ms CPU time.
Sep 07 18:29:20 ubnt systemd[1]: Started NextDNS DNS53 to DoH proxy..
Sep 07 18:29:20 ubnt nextdns[2509]: Starting NextDNS 1.37.1/linux on :53
Sep 07 18:29:20 ubnt nextdns[2509]: Listening on TCP/:53
Sep 07 18:29:20 ubnt nextdns[2509]: Starting mDNS discovery
Sep 07 18:29:20 ubnt nextdns[2509]: Listening on UDP/:53
Sep 07 18:29:20 ubnt nextdns[2509]: Startup failed: proxy: tcp: listen tcp :53: bind: address already in use
Sep 07 18:29:20 ubnt nextdns[2509]: Error: proxy: tcp: listen tcp :53: bind: address already in use
Sep 07 18:29:20 ubnt systemd[1]: nextdns.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 18:29:20 ubnt systemd[1]: nextdns.service: Failed with result 'exit-code'.
Sep 07 18:29:20 ubnt systemd[1]: nextdns.service: Consumed 19ms CPU time.
```

**Comment by janthony6** [comment]
> I experienced the same. The issue seems to be with the `podman cp` command.
> 
> https://github.com/nextdns/nextdns/blob/6e203b0cbc7fb9a890e7bb9f389accb3d02e459e/install.sh#L460
> 
> I ran the commands from the install.sh file manually, but instead of `echo` to a file to be copied into the container, I used `podman exec` to echo directly to the final location of the file and everything worked as expected. On this beta firmware (same as OP) the podman version is `1.6.1`.

can you explain these commands that you entered?

**Comment by owine** [comment]
> > I experienced the same. The issue seems to be with the `podman cp` command.
> > https://github.com/nextdns/nextdns/blob/6e203b0cbc7fb9a890e7bb9f389accb3d02e459e/install.sh#L460
> > 
> > I ran the commands from the install.sh file manually, but instead of `echo` to a file to be copied into the container, I used `podman exec` to echo directly to the final location of the file and everything worked as expected. On this beta firmware (same as OP) the podman version is `1.6.1`.
> 
> can you explain these commands that you entered?
These are run on the UDM, not in the unifi-so container. 

``` 
    podman exec unifi-os echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" > /etc/apt/sources.list.d/nextdns.list
    podman exec unifi-os apt-get install -y gnupg1 curl
    podman exec unifi-os curl -sfL https://repo.nextdns.io/nextdns.gpg -o /usr/share/keyrings/nextdns.gpg
    podman exec unifi-os apt-get update -o Dir::Etc::sourcelist="sources.list.d/nextdns.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
```

**Comment by janthony6** [comment]
that doesn't work for me. 

```
# podman exec unifi-os echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] htt
ps://repo.nextdns.io/deb stable main" > /etc/apt/sources.list.d/nextdns.list
-sh: can't create /etc/apt/sources.list.d/nextdns.list: nonexistent directory
```

**Comment by owine** [comment]
> that doesn't work for me.
> 
> ```
> # podman exec unifi-os echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] htt
> ps://repo.nextdns.io/deb stable main" > /etc/apt/sources.list.d/nextdns.list
> -sh: can't create /etc/apt/sources.list.d/nextdns.list: nonexistent directory
> ```

I can’t remember exactly, but I may have run
`podman exec unifi-os touch /etc/apt/sources.list.d/nextdns.list` before the other commands

**Comment by janthony6** [comment]
```
# podman exec unifi-os touch /etc/apt/sources.list.d/nextdns.list
# podman exec unifi-os echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" > /etc/apt/sources.list.d/nextdns.list
-sh: can't create /etc/apt/sources.list.d/nextdns.list: nonexistent directory
```

**Comment by vincentbernat** [comment]
```

**Comment by rs** [comment]
After installing from withing the unifi-os shell, do you have setup-router to true?

**Comment by janthony6** [comment]
Yes. Setup router is true. It still listens on 53.

**Comment by rs** [comment]
What do you get for `ls -ld /etc/unifi-base-ucore` from unifi-os shell?

**Comment by janthony6** [comment]
```
# unifi-os shell
root@ubnt:/# ls -ld /etc/unifi-base-ucore
ls: cannot access '/etc/unifi-base-ucore': No such file or directory
root@ubnt:/# 
```

**Comment by rs** [comment]
What is the output of `ls -l /etc`?

**Comment by Veldkornet** [comment]
That command works for me on ubios (UDMP 1.11.0-14)

```
Status:      Connected (http://localhost:8080/inform)
# unifi-os shell
root@ubnt:/# ls -ld /etc/unifi-base-ucore
drwxr-xr-x 2 root root 3 Jul 23 18:51 /etc/unifi-base-ucore
```

**Comment by janthony6** [comment]
```
root@ubnt:/# ls -l /etc?                 
ls: cannot access '/etc?': No such file or directory
root@ubnt:/# 
```

**Comment by janthony6** [comment]
when I run from the UDM (not unifi-os shell) I get this:

```
# ls -l /etc
total 213
drwxr-xr-x    1 root     root            80 Aug 13 00:44 Wireless
drwxr-xr-x    3 root     root            98 Aug 13 00:49 avahi
-rw-r--r--    1 root     root           919 Sep  7 19:37 board.info
drwxr-xr-x    3 root     root            28 Aug 13 00:28 cni
drwxr-xr-x    2 root     root           116 Aug 13 00:28 containers
drwxr-xr-x    1 root     root           140 Sep  7 19:42 cron.d
drwxr-xr-x    2 root     root             3 Aug 13 00:18 cron.daily
drwxr-xr-x    1 root     root            80 Sep  7 19:37 cron.hourly
drwxr-xr-x    2 root     root             3 Aug 13 00:18 cron.monthly
drwxr-xr-x    2 root     root             3 Aug 13 00:18 cron.weekly
drwxr-xr-x    3 root     root            70 Aug 13 00:00 dbus-1
drwxr-xr-x    2 root     root            69 Jul 20 08:35 default
-rw-r--r--    1 root     root          3901 Jul 20 08:35 default-ea11.cfg
lrwxrwxrwx    1 root     root            16 Jul 20 08:35 default-ea13.cfg -> default-ea11.cfg
-rw-r--r--    1 root     root           492 Jul 20 08:35 default-ea15.cfg
drwxr-xr-x    2 root     root            80 Sep  7 19:37 dropbear
-rw-r--r--    1 root     root            97 Aug 12 23:58 environment
-rw-r--r--    1 root     root          1317 Aug 13 00:19 ethertypes
-rw-r--r--    1 root     root           598 Aug 13 00:49 fstab
-rw-r--r--    1 root     root           338 Aug 13 00:50 group
drwxr-xr-x    2 root     root            80 Sep  7 19:37 hostapd
-rw-r--r--    1 root     root        107391 Aug 13 00:44 hostapd.conf
-rw-r--r--    1 root     root             4 Sep  7 19:37 hostname
-rw-r--r--    1 root     root            94 Sep  7 19:37 hosts
-rw-------    1 root     root           183 Aug 13 00:24 inadyn.conf
drwxr-xr-x    2 root     root           802 Jul 20 08:35 init.d
-rw-r--r--    1 root     root          1829 Sep  7 19:37 inittab
-rw-r--r--    1 root     root          1180 Aug 12 23:58 inputrc
drwxr-xr-x    2 root     root           168 Aug 13 00:24 iproute2
-rw-r--r--    1 root     root           193 Jul 20 08:35 issue
drwxr-xr-x    2 root     root            44 Aug 13 00:20 libnl
-rw-r--r--    1 root     root           176 Sep  7 19:37 lldpd.conf
drwxr-xr-x    2 root     root            34 Aug 13 00:29 lldpd.d
lrwxrwxrwx    1 root     root            39 Sep  7 19:38 localtime -> /usr/share/zoneinfo/America/Los_Angeles
-rw-r--r--    1 root     root           241 Sep  7 19:37 marks.cfg
-rw-r--r--    1 root     root            16 Sep  7 19:37 mediatek.conf
-rw-r--r--    1 root     root           808 Aug 13 00:19 mke2fs.conf
-rw-r--r--    1 root     root           276 Jul 20 08:35 motd
lrwxrwxrwx    1 root     root            19 Jul 20 08:35 mtab -> ../proc/self/mounts
drwxr-xr-x    6 root     root           106 Jul 20 08:35 network
-rw-r--r--    1 root     root           230 Aug 13 00:49 nsswitch.conf
lrwxrwxrwx    1 root     root            21 Aug 13 00:33 os-release -> ../usr/lib/os-release
-rw-r--r--    1 root     root           182 Aug 13 00:23 ospfd.conf.sample
drwxr-xr-x    2 root     root            65 Aug 13 00:33 pam.d
-rw-r--r--    1 root     root           492 Dec 31  1969 passwd
lrwxrwxrwx    1 root     root            20 Aug 13 00:49 pkg-release -> /usr/lib/pkg-release
drwxr-xr-x    3 root     root            29 Aug 13 00:31 ppp
-rw-r--r--    1 root     root           324 Jul 20 08:35 profile
drwxr-xr-x    2 root     root            66 Jul 28 19:51 profile.d
-rw-r--r--    1 root     root          2744 Jul 20 08:35 protocols
-rw-------    1 root     root           512 Sep  7 19:37 random-seed
-rw-r--r--    1 root     root            57 Aug 13 00:36 required-users
lrwxrwxrwx    1 root     root            18 Jul 20 08:35 resolv.conf -> ../tmp/resolv.conf
lrwxrwxrwx    1 root     root            19 Sep  7 19:37 resolv.dnsmasq -> /tmp/resolv.dnsmasq
-rw-r--r--    1 root     root           325 Aug 13 00:23 ripngd.conf.sample
drwxr-xr-x    1 root     root            60 Dec 31  1969 security
drwxr-xr-x    2 root     root             3 Aug 13 00:29 sensors.d
-rw-r--r--    1 root     root         10215 Aug 13 00:29 sensors3.conf
-rw-r--r--    1 root     root         10873 Jul 20 08:35 services
-rw-------    1 root     root           339 Dec 31  1969 shadow
-rw-r--r--    1 root     root          6699 Aug 13 00:31 smartd.conf
drwxr-xr-x    2 root     root             3 Aug 13 00:31 smartd_warning.d
-rwxr-xr-x    1 root     root          5847 Aug 13 00:31 smartd_warning.sh
drwxr-xr-x    6 root     root            85 Aug 13 00:17 ssl
-rw-r--r--    1 root     root           200 Sep  7 19:37 startup.list
-r--r-----    1 root     root          3174 Aug 13 00:33 sudoers
drwxr-x---    2 root     root             3 Aug 13 00:33 sudoers.d
-r--r-----    1 root     root          3174 Aug 13 00:33 sudoers.dist
drwxr-xr-x    2 root     root            52 Aug 13 00:33 sysconfig
drwxr-xr-x    2 root     root           355 Jul 20 08:35 sysctl.d
drwxr-xr-x    2 root     root           400 Sep  7 19:37 sysinit
-rw-r--r--    1 root     root            29 Jul 20 08:35 syslog.conf
-rw-r--r--    1 root     root            20 Sep  7 19:38 timezone
drwxr-xr-x    3 root     root            33 Aug 13 00:37 ubnt
-rw-r--r--    1 root     root           128 Aug 13 00:23 vtysh.conf.sample
-rw-r--r--    1 root     root           305 Aug 13 00:23 zebra.conf.sample
```

**Comment by rs** [comment]
Please run it from the unifi-os shell without the `?` at the end (just `ls -l /etc`)

**Comment by janthony6** [comment]
Whoops! yeah that's better. Here is from unifi-os shell:

```
# unifi-os shell
root@ubnt:/# ls -l /etc
total 277
drwxr-xr-x 5 root root     136 Aug 12 06:50 X11
-rw-r--r-- 1 root root    2981 Oct 13  2019 adduser.conf
-rw-r--r-- 1 root root     185 Aug 12 06:43 aliases
drwxr-xr-x 1 root root    4096 Sep  7 18:49 alternatives
drwxr-xr-x 1 root root    4096 Oct 13  2019 apt
drwxr-xr-x 3 root root      69 Aug 12 06:39 avahi
-rw-r--r-- 1 root root    1863 May 15  2017 bash.bashrc
-rw-r--r-- 1 root root     367 Mar  2  2018 bindresvport.blacklist
drwxr-xr-x 2 root root       3 Jul 21  2019 binfmt.d
drwxr-xr-x 3 root root      31 Aug 12 06:37 ca-certificates
-rw-r--r-- 1 root root    5989 Aug 12 06:37 ca-certificates.conf
drwxr-xr-x 2 root root      35 Aug 12 06:43 cron.d
drwxr-xr-x 2 root root     114 Aug 12 06:43 cron.daily
drwxr-xr-x 2 root root      35 Aug 12 06:43 cron.hourly
drwxr-xr-x 2 root root      35 Aug 12 06:43 cron.monthly
drwxr-xr-x 2 root root      35 Aug 12 06:43 cron.weekly
-rw-r--r-- 1 root root     722 Oct  7  2017 crontab
drwxr-xr-x 4 root root      48 Aug 12 06:39 dbus-1
-rw-r--r-- 1 root root    2969 May 21  2017 debconf.conf
-rw-r--r-- 1 root root       5 Sep  8  2019 debian_version
drwxrwxr-x 3 root root     268 Aug 12 06:50 default
-rw-r--r-- 1 root root     604 Jun 26  2016 deluser.conf
drwxr-xr-x 3 root root      44 Oct 16  2019 dhcp
drwxrwxr-x 4 root root     109 Aug 12 06:35 dpkg
-rw-r--r-- 1 root root     312 May  4 02:03 email-addresses
-rw-r--r-- 1 root root       0 Oct 13  2019 environment
drwxr-xr-x 3 root root     107 Aug 12 06:43 exim4
drwxr-xr-x 4 root root      65 Aug 12 06:50 fonts
-rw-r--r-- 1 root root      37 Oct 13  2019 fstab
-rw-r--r-- 1 root root    2584 Aug  1  2016 gai.conf
-rw-r--r-- 1 root root     917 Sep  7 18:49 group
-rw-r--r-- 1 root root     893 Aug 12 06:43 group-
-rw-r----- 1 root shadow   570 Sep  7 18:49 gshadow
-rw-r----- 1 root shadow   548 Aug 12 06:43 gshadow-
drwxr-xr-x 3 root root      29 Aug 12 06:36 gss
-rw-r--r-- 1 root root       9 Aug  7  2006 host.conf
-rw-r--r-- 1 root root       4 Sep  7 19:37 hostname
-rw-r--r-- 1 root root     109 Sep  7 19:37 hosts
-rw-r--r-- 1 root root     411 Aug 12 06:43 hosts.allow
-rw-r--r-- 1 root root     711 Aug 12 06:43 hosts.deny
drwxr-xr-x 2 root root      78 Aug 12 06:53 init
drwxr-xr-x 1 root root    4096 Sep  7 18:50 init.d
-rw-r--r-- 1 root root    1748 May 15  2017 inputrc
-rw-r--r-- 1 root root      26 Sep  8  2019 issue
-rw-r--r-- 1 root root      19 Sep  8  2019 issue.net
drwxr-xr-x 5 root root     356 Aug 12 06:51 java-8-openjdk
drwxr-xr-x 4 root root      50 Oct 16  2019 kernel
-rw-r--r-- 1 root root   20220 Sep  7 18:50 ld.so.cache
-rw-r--r-- 1 root root      34 Mar  2  2018 ld.so.conf
drwxr-xr-x 2 root root      62 Oct 13  2019 ld.so.conf.d
drwxr-xr-x 2 root root      32 Aug 12 06:37 ldap
-rw-r--r-- 1 root root     191 Apr 12  2017 libaudit.conf
-rw-r--r-- 1 root root    2995 Feb  6  2019 locale.alias
-rw-r--r-- 1 root root    9098 Aug 12 06:45 locale.gen
lrwxrwxrwx 1 root root      41 Sep  7 18:50 localtime -> ../usr/share/zoneinfo/America/Los_Angeles
-rw-r--r-- 1 root root   10477 May 17  2017 login.defs
-rw-r--r-- 1 root root     599 May  5  2015 logrotate.conf
drwxr-xr-x 1 root root    4096 Sep  7 18:50 logrotate.d
-rw-r--r-- 1 root root      33 Oct 13  2019 machine-id
-rw-r--r-- 1 root root     111 Oct 22  2019 magic
-rw-r--r-- 1 root root     111 Oct 22  2019 magic.mime
-rw-r--r-- 1 root root    1604 Aug 12 06:43 mailcap
-rw-r--r-- 1 root root     449 May  1  2016 mailcap.order
-rw-r--r-- 1 root root      10 Aug 12 06:43 mailname
-rw-r--r-- 1 root root   24301 May  1  2016 mime.types
-rw-r--r-- 1 root root     973 Jan 31  2017 mke2fs.conf
drwxr-xr-x 2 root root      35 Aug 12 06:40 modules-load.d
-rw-r--r-- 1 root root    2143 Aug 24  2020 mongodb.conf
-rw-r--r-- 1 root root     286 Sep  8  2019 motd
lrwxrwxrwx 1 root root      19 Sep  7 18:49 mtab -> ../proc/self/mounts
drwxr-xr-x 3 root root      66 Aug 12 06:43 mysql
-rw-r--r-- 1 root root    8769 Jan 10  2017 nanorc
drwxr-xr-x 4 root root      52 Aug 12 06:39 network
-rw-r--r-- 1 root root      60 Aug 12 06:43 networks
-rw-r--r-- 1 root root     307 Sep  7 19:01 nextdns.conf
drwxr-xr-x 2 root root       3 Apr 13 00:41 node12
-rw-r--r-- 1 root root     528 Aug 12 06:39 nsswitch.conf
drwxr-xr-x 2 root root       3 Oct 13  2019 opt
lrwxrwxrwx 1 root root      21 Sep  8  2019 os-release -> ../usr/lib/os-release
-rw-r--r-- 1 root root     552 May 27  2017 pam.conf
drwxr-xr-x 1 root root    4096 Sep  7 18:50 pam.d
-rw-r--r-- 1 root root    2059 Sep  7 18:49 passwd
-rw-r--r-- 1 root root    1996 Aug 12 06:43 passwd-
drwxr-xr-x 4 root root      62 Aug 12 06:37 perl
drwxr-xr-x 1 root root    4096 Sep  7 18:49 postgresql
drwxr-xr-x 3 root root     131 Aug 12 06:44 postgresql-common
drwxr-xr-x 3 root root      30 Aug 12 06:43 ppp
-rw-r--r-- 1 root root     767 Mar  4  2016 profile
drwxr-xr-x 2 root root       3 Sep  8  2019 profile.d
-rw-r--r-- 1 root root    2932 Dec 25  2016 protocols
drwxr-xr-x 2 root root      39 Aug 12 06:43 python2.7
drwxr-xr-x 2 root root      36 Aug 12 06:44 python3
drwxr-xr-x 2 root root      39 Aug 12 06:43 python3.5
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc0.d
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc1.d
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc2.d
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc3.d
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc4.d
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc5.d
drwxr-xr-x 1 root root    4096 Sep  7 18:50 rc6.d
drwxr-xr-x 2 root root      74 Aug 12 06:50 rcS.d
-rw-r--r-- 1 root root      21 Sep  7 19:37 resolv.conf
drwxr-xr-x 3 root root      36 Aug 12 06:39 resolvconf
-rwxr-xr-x 1 root root     268 Oct 29  2016 rmt
-rw-r--r-- 1 root root     887 Dec 25  2016 rpc
-rw-r--r-- 1 root root    4179 May 17  2017 securetty
drwxr-xr-x 4 root root     223 Oct 13  2019 security
drwxr-xr-x 2 root root      36 Oct 13  2019 selinux
-rw-r--r-- 1 root root   19183 Dec 25  2016 services
-rw-r----- 1 root shadow   737 Sep  7 18:49 shadow
-rw-r----- 1 root shadow   705 Aug 12 06:43 shadow-
-rw-r--r-- 1 root root      73 Oct 13  2019 shells
drwxr-xr-x 2 root root      66 Oct 13  2019 skel
-rw-r--r-- 1 root root    7056 Jul 30  2016 smartd.conf
drwxr-xr-x 4 root root      52 Aug 12 06:47 smartmontools
drwxr-xr-x 2 root root      47 Aug 12 06:38 ssh
drwxr-xr-x 4 root root      62 Aug 12 06:37 ssl
-rw-r--r-- 1 root root     771 Jun  9  2012 staff-group-for-usr-local
-rw-r--r-- 1 root root       0 Oct 13  2019 subgid
-rw-r--r-- 1 root root       0 Oct 13  2019 subuid
-r--r----- 1 root root     669 Jan 23  2021 sudoers
drwxr-xr-x 2 root root      61 Aug 12 06:47 sudoers.d
-rw-r--r-- 1 root root    2683 May 17  2018 sysctl.conf
drwxr-xr-x 2 root root      88 Aug 12 06:43 sysctl.d
drwxrwxr-x 1 root root    4096 Aug 12 06:35 systemd
drwxr-xr-x 2 root root      29 Oct 13  2019 terminfo
-rw-r--r-- 1 root root      20 Sep  7 18:50 timezone
drwxr-xr-x 2 root root       3 Jul 21  2019 tmpfiles.d
-rw-r--r-- 1 root root    1260 Mar 16  2016 ucf.conf
drwxr-xr-x 2 root root       3 Aug  9 10:48 unifi-core
drwxr-xr-x 2 root root    4096 Sep  7 18:48 unifi-os
drwxr-xr-x 2 root root      31 Oct 13  2019 update-motd.d
drwxr-xr-x 3 root root      30 Oct 16  2019 xdg
root@ubnt:/# 
```

**Comment by rs** [comment]
Is that an UDM or UDM Pro?

**Comment by janthony6** [comment]
That is a UDM on 1.11b4 firmware.

**Comment by rs** [comment]
Ok, so I think we broke UDM (non Pro) support with this revision. Back to the drawing board.

**Comment by janthony6** [comment]
seems this is fixed now with the latest snapshot:

`NEXTDNS_VERSION=master/SNAPSHOT-90dca2e sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'`

**Comment by owine** [comment]
Just to circle on this, I believe there are two separate issues in this issue/thread and I want to make sure the second one is not lost.

1) Detection on UDM (non-Pro) - reportedly fixed with 1.37.2 release

2) Installer adding the repo on UDM/P beta firmware - does not yet appear to be fixed

**Comment by Veldkornet** [comment]
I manually added the repo so that I could upgrade, although I still see this freezer.state error message

```

sh -c 'sh -c "$(curl -sL https://nextdns.io/install)"'
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.2
u) Upgrade NextDNS from 1.37.1 to 1.37.2
c) Configure NextDNS
r) Remove NextDNS
e) Exit
Choice (default=u): u
INFO: Upgrading NextDNS...
no such directory for freezer.state
Error: `/usr/bin/runc pause 01242cd40801fc2ebbeba4c1c023e3b2ab14b50a08d2effa612d82bb2dd76a03` failed: exit status 1
Reading package lists...
Building dependency tree...
Reading state information...
gnupg1 is already the newest version (1.4.21-4+deb9u1).
curl is already the newest version (7.52.1-5+deb9u15).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Get:1 https://repo.nextdns.io/deb stable InRelease [9398 B]Get:2 https://repo.nextdns.io/deb stable/main arm64 Packages [422 B]
Fetched 9820 B in 0s (10.7 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be upgraded:
  nextdns
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3061 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://repo.nextdns.io/deb stable/main arm64 nextdns arm64 1.37.2 [3061 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 3061 kB in 1s (2381 kB/s)
(Reading database ... 68827 files and directories currently installed.)
Preparing to unpack .../nextdns_1.37.2_arm64.deb ...
Unpacking nextdns (1.37.2) over (1.37.1) ...
#-> ubnt-dpkg-cache unpack
removing /data/dpkg-cache/stretch/packages/nextdns_1.37.1_arm64.deb ... done
nextdns: action=unpack, package=/data/dpkg-cache/stretch/packages/nextdns_1.37.2_arm64.deb mark=manual
<-# ubnt-dpkg-cache unpack
Setting up nextdns (1.37.2) ...
NextDNS installed and started using ubios init
```

**Comment by rs** [comment]
> 2. Installer adding the repo on UDM/P beta firmware - does not yet appear to be fixed

@owine can you tell me more about this one? What would be the fix?

**Comment by Veldkornet** [comment]
The repository was missing for me too, I had to add it back manually with the below:

```
unifi-os shell

echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" >> /etc/apt/sources.list.d/nextdns.list
```

**Comment by janthony6** [comment]
I'm using the latest snapshot on the UDM. 1.37.2 does not install on the UDM for me.

**Comment by janthony6** [comment]
adding the repo got it to install. thanks!

**Comment by janthony6** [comment]
on another machine even after adding the repo, I get this:

```
root@ubnt:/# sudo nextdns upgrade
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.2
INFO: Upgrading NextDNS...
Ign:1 http://deb.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch-backports InRelease
Hit:5 http://deb.debian.org/debian stretch Release 
Hit:6 https://deb.nodesource.com/node_8.x stretch InRelease
Hit:7 https://apt.artifacts.ui.com stretch InRelease
Get:8 https://repo.nextdns.io/deb stable InRelease [9398 B]
Ign:8 https://repo.nextdns.io/deb stable InRelease         
Fetched 9398 B in 1s (6968 B/s)
Reading package lists... Done
W: GPG error: https://repo.nextdns.io/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467A7CCC8ACFA0B7
W: The repository 'https://repo.nextdns.io/deb stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/nextdns.list:1 and /etc/apt/sources.list.d/nextdns.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nextdns.list:1 and /etc/apt/sources.list.d/nextdns.list:2
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/nextdns.list:1 and /etc/apt/sources.list.d/nextdns.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nextdns.list:1 and /etc/apt/sources.list.d/nextdns.list:2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  nextdns
1 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Need to get 3061 kB of archives.
After this operation, 0 B of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  nextdns
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list.d/nextdns.list:1 and /etc/apt/sources.list.d/nextdns.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/nextdns.list:1 and /etc/apt/sources.list.d/nextdns.list:2
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Error: exit status 100
root@ubnt:/# 
```

**Comment by janthony6** [comment]
this worked:
add repo after unifi-os shell. then exit shell and run nextdns upgrade - that got it to install and run.

**Comment by owine** [comment]
> > 1. Installer adding the repo on UDM/P beta firmware - does not yet appear to be fixed
> 
> @owine can you tell me more about this one? What would be the fix?

@rs there seems to be a regression on the beta firmware whereby the `podman cp` command to add the repo gives an error such as:
```
no such directory for freezer.state
Error: `/usr/bin/runc pause 01242cd40801fc2ebbeba4c1c023e3b2ab14b50a08d2effa612d82bb2dd76a03` failed: exit status 1
```

I manually used `echo` to add the repo in the `unifi-os` container - this would likely work as well: https://github.com/nextdns/nextdns/issues/563#issuecomment-914925124

**Comment by rs** [comment]
I pushed a fix in the installer. Please try a fresh install (from scratch if possible) and confirm.

**Comment by janthony6** [comment]
should that be a snapshot install or the same 1.37.2

**Comment by owine** [comment]
> I pushed a fix in the installer. Please try a fresh install (from scratch if possible) and confirm.

@rs I cannot test from scratch at the moment, however this does not seem to have worked - I have `/etc/apt/sources.list.d/nextdns.list` but the file is now blank. Previously I had the repo loaded just fine, but the proposed fix makes the file empty and does not repopulate it.

**Comment by rs** [comment]
I'm not surprise, reverting. @vincentbernat another idea?

**Comment by Nnyan** [comment]
I was running v1.36.0 when I attempted to upgrade.  Had and error and my DNS broke, but changed it from 127.0.0.1 in the Unifi Controller got my DNS back up.  Followed this thread and was able to get this installed properly but just wanted to give some feedback in case it's helpful

admin@ubnt:~$ nextdns version
nextdns version 1.36.0
admin@ubnt:~$ nextdns status
running
admin@ubnt:~$ nextdns upgrade
INFO: OS: edgeos
INFO: GOARCH: mips64_softfloat
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /config/nextdns/nextdns
INFO: INSTALL_RELEASE: 1.37.2
INFO: Upgrading NextDNS...
NextDNS installed and started using edgeos init
Error: /config/scripts/post-config.d/nextdns.sh start: exit status 1: Error: proxy: tcp: listen tcp 127.0.0.1:53: bind: address already in use

admin@ubnt:~$ nextdns status
stopped
admin@ubnt:~$ nextdns start
Error: /config/scripts/post-config.d/nextdns.sh start: exit status 1: /config/scripts/post-config.d/nextdns.sh: line 29: /tmp/nextdns.pid: Permission denied
Error: proxy: tcp: listen tcp 10.0.0.1:53: bind: permission denied

admin@ubnt:~$ sudo nextdns config set -setup-router
admin@ubnt:~$ nextdns status
stopped
admin@ubnt:~$ nextdns start
Error: /config/scripts/post-config.d/nextdns.sh start: exit status 1: /config/scripts/post-config.d/nextdns.sh: line 29: /tmp/nextdns.pid: Permission denied
Error: proxy: tcp: listen tcp :53: bind: permission denied

At this point I found this thread I believe and uninstalled and reinstalled and it's back up and running.

**Comment by janthony6** [comment]
On your UniFi controller, you shouldn't have your dns set to 127.x. Leave it blank.

**Comment by Nnyan** [comment]
I was seeing duplicate entries in my logs.  I did some research and found a number of posts like this one:  https://www.chriscolotti.us/technology/nextdns-now-works-with-the-ubiquiti-secure-gateway/

When I made the change to the controller those went away.

**Comment by janthony6** [comment]
that article is wrong. that's not the solution. the solution is to remove anything there and just wait. 100% of your dns lookups will be encrypted. Inputting that setting will cause your controller to go offline within a day and only be accessible locally, among other issues.

**Comment by insibasimon** [comment]
> this worked:
> add repo after unifi-os shell. then exit shell and run nextdns upgrade - that got it to install and run.

This also worked for me @rs

**Comment by Nnyan** [comment]
Thank you for the info janthony6 made the change.

**Comment by mojo333** [comment]
> > this worked:
> > add repo after unifi-os shell. then exit shell and run nextdns upgrade - that got it to install and run.
> 
> This also worked for me @rs

And for me too...

**Comment by Veldkornet** [comment]
> The repository was missing for me too, so when I tried to update it ran through the process but did nothing. I had to add it back manually with the below:
> 
> ```
> unifi-os shell
> 
> echo "deb [signed-by=/usr/share/keyrings/nextdns.gpg] https://repo.nextdns.io/deb stable main" >> /etc/apt/sources.list.d/nextdns.list
> 
> exit
> ```

I noticed today that the upgrade wasn't working again. Had to run the above echo command again to get things working.

**Comment by erbeh77** [comment]
better, still having some issues:


# sudo nextdns activate
Error: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy
Error: non zero exit code: 1: OCI runtime error
# sudo nextdns upgrade
INFO: OS: ubios
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /data/nextdns
INFO: INSTALL_RELEASE: 1.37.3
INFO: Already on the latest version
INFO: OS: debian
INFO: GOARCH: arm64
INFO: GOOS: linux
INFO: NEXTDNS_BIN: /usr/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.3
INFO: Already on the latest version
#
# sudo nextdns activate
Error: setup resolv.conf: rename /etc/resolv.conf /etc/resolv.conf.nextdns-bak: device or resource busy
Error: non zero exit code: 1: OCI runtime error
