### ISSUE TITLE
Tiny bug possibly caused by HomeBrew path defaulting to /opt/homebrew on Apple M1

### ISSUE THREAD

**Issue by ink-splatters** [nextdns/nextdns#600]
**Context**
 - CLI Version: 1.37.3
 - Platform: Darwin arm64

Hi, seems super easy to fix:

`sudo nextdns config wizard` is expecting the cli to be located at `/usr/local/bin/nextdns` which is not the default location on Apple M1 machines

```
✖1 ❯ sudo nextdns config wizard
INFO: OS: darwin
INFO: GOARCH: arm64
INFO: GOOS: darwin
INFO: NEXTDNS_BIN: /usr/local/bin/nextdns
INFO: INSTALL_RELEASE: 1.37.3
sh: line 590: /usr/local/bin/nextdns: No such file or directory
```

Best regards,
Peter

**Comment by ink-splatters** [comment]
Hi, 

sorry for being late responder and also for having mislead you with the ticket header. Indeed, it's not caused by `HomeBrew`, at least because `nextcli` is not presented in `HomeBrew` whatsoever :) (`brew search nextdns` gave nothing).

Instead, seems `HomeBrew` works around possibly missing `/usr/local` on Apple M1 machines, in some cases, by having chosen `/opt/homebrew` as a default location instead. That's sort of rumor and needs more investigation, but I'm ok with "rumor" term in this context because it doesn't actually matter. 

My main point is: why need to hardcode binary path?

I'm not sure what's the app logic is, but, presuming you need an access to executable itself (patching?): having `nextdns` in `PATH` might be not sufficient. 

Just in case it helps (disregard otherwise):

you could use the path from `argv[0]` which might work in most of the cases, but there's no guarantee.

To my best knowledge, the best way of _reliably_ getting the full exe path is using platform specific way:

[https://www.reddit.com/r/C_Programming/comments/dgcmhd/comment/f3as9yq/](https://www.reddit.com/r/C_Programming/comments/dgcmhd/comment/f3as9yq/)

So, could you share your opinion about that?

**Comment by rs** [comment]
This is already fixed, please see 67dee3f

**Comment by alexmerm** [comment]
Hi, 
So I saw the fix mentioned above, but  there is still an issue in the `install_type()` function at  https://github.com/nextdns/nextdns/blob/3e26ffdd37f9a177d0b469d4507510406375214e/install.sh#L566-L572 where it only looks to see if brew is installed at the x86 home directory, rather than also looking in the M1 directory  `/usr/local/homebrew/bin/brew`

It's only an issue for people that have brew, but are using the nextDNS installer script, but it should be an easy fix (just checking for either directory works)
