### ISSUE TITLE
Arch Linux install instructions

### ISSUE THREAD

**Issue by PitcherTear22** [nextdns/nextdns#94]
yay is an AUR package, ```sudo pacman -S yay``` won't work

**Comment by rs** [comment]
What would be the right instruction? I have no xp with arch, instructions comes from the package maintainer (cc @tanji).

**Comment by ChiDal** [comment]
Idk maybe this?

Use an AUR helper like [yay](https://github.com/Jguer/yay)
`yay -S nextdns`
or install the package manually
`git clone htpps://aur.archlinux.org/nextdns.git
cd nextdns
makepkg -si`

**Comment by rs** [comment]
I guess you need to install yay before using it. Hence the `pacman -S yay`. Am I missing something?

**Comment by ChiDal** [comment]
> I guess you need to install yay before using it. Hence the `pacman -S yay`. Am I missing something?

You can't install yay using pacman because yay isn't in the official repos

**Comment by digital-mystik** [comment]
The Arch Wiki has AUR package installation instructions here:
https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages

If you would like to use yay, you can follow this:
https://github.com/Jguer/yay#installation

Off-topic but I would recommend going through the wiki first and understand what AUR helpers are actually doing, and familiarize yourself with PGKBUILDs

**Comment by ChiDal** [comment]
> The Arch Wiki has AUR package installation instructions here:
> 
> https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages
> 
> If you would like to use yay, you can follow this to install it:
> 
> https://github.com/Jguer/yay#installation
> 
> then: `yay -S nextdns`
> 
> Off-topic but I would recommend going through the wiki first and understand what AUR helpers are actually doing, and familiarize yourself with PKGBUILDs

Yes I know. Read the issue first

**Comment by digital-mystik** [comment]
> > The Arch Wiki has AUR package installation instructions here:
> > https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages
> > If you would like to use yay, you can follow this to install it:
> > https://github.com/Jguer/yay#installation
> > then: `yay -S nextdns`
> > Off-topic but I would recommend going through the wiki first and understand what AUR helpers are actually doing, and familiarize yourself with PKGBUILDs
> 
> Yes I know. Read the issue first

I misunderstood; thought you were asking how to install it or was having trouble doing so. My apologies.

**Comment by ChiDal** [comment]
Sorry for being rude

**Comment by PitcherTear22** [comment]
this one seems fixed now, except the package is not a binary

**Comment by tanji** [comment]
@rs can you give me permissions to edit the Wiki?

**Comment by tanji** [comment]
@rs still not working :(

https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

As a collaborator I should be able to Edit, but no... button doesn't show up

**Comment by rs** [comment]
Wiki edits is now public. Let’s see how it goes.

**Comment by tanji** [comment]
@rs updated the wiki. you can close this issue

**Comment by rs** [comment]
Thx
